# Form implementation generated from reading ui file 'fileexplorer/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lentele = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.lentele.setGeometry(QtCore.QRect(10, 70, 781, 501))
        self.lentele.setObjectName("lentele")
        self.lentele.setColumnCount(3)
        self.lentele.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lentele.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lentele.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lentele.setHorizontalHeaderItem(2, item)
        self.lentele.horizontalHeader().setDefaultSectionSize(150)
        self.Atgal = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Atgal.setGeometry(QtCore.QRect(14, 30, 401, 23))
        self.Atgal.setObjectName("Atgal")
        self.naujas_failas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.naujas_failas.setGeometry(QtCore.QRect(430, 30, 361, 23))
        self.naujas_failas.setObjectName("naujas_failas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.lentele.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pavadinimas"))
        item = self.lentele.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tipas"))
        item = self.lentele.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Paskutine modifikacija"))
        self.Atgal.setText(_translate("MainWindow", "Atgal"))
        self.naujas_failas.setText(_translate("MainWindow", "Naujas failas"))
